name: Cypress Tests - Example project

on:
  push:
    branches:
      - main
    paths:
      - '**.js'
      - '**.json'
      - '**.yml'

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.16.0
      
      - name: Install depedencies
        run: |
          echo "Install NPM libraries"
          npm install
          echo "Install cypress depedencies"
          cypress install

      - name: Run Cypress tests
        run: npm run cypress:headless